CREATE TABLE `PRODUCTS` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `CODE` VARCHAR (25) NOT NULL,
    `NAME` VARCHAR (250) NOT NULL,
    `UNIT` VARCHAR (10) NOT NULL,
    `RESIDUAL` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `DEFAULT_PURCHASE_PRICE` DECIMAL (10, 2) NOT NULL DEFAULT 0,
    `DEFAULT_PURCHASE_PRICE_USD` DECIMAL (10, 2) NOT NULL DEFAULT 0,
    `DEFAULT_SALE_PRICE` DECIMAL (10, 2) NOT NULL DEFAULT 0
);

CREATE FULLTEXT INDEX `UNIQUE_PRODUCT_CODE` ON `PRODUCTS`(`CODE`);
CREATE FULLTEXT INDEX `PRODUCT_NAME` ON `PRODUCTS`(`NAME`);