CREATE TABLE `INCOME_ORDER` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `COMMENT` TEXT DEFAULT NULL,
    `DATE_CREATED` TIMESTAMP NOT NULL
);

CREATE TABLE `INCOME` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` INT(11) NOT NULL,
    `INCOME_ORDER_ID` INT(11) NOT NULL,
    `INCOME_PRICE` DECIMAL(10, 2) NOT NULL,
    `INCOME_PRICE_USD` DECIMAL(10, 2) NOT NULL,
    `AMOUNT` DECIMAL(10, 2) NOT NULL,
    `RESIDUAL` DECIMAL(10, 2) NOT NULL DEFAULT 0,
    `HAS_MORE` TINYINT(1) DEFAULT 1,
    CONSTRAINT `fk_INCOME_TO_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS`(`ID`),
    CONSTRAINT `fk_INCOME_TO_INCOME_ORDER` FOREIGN KEY (`INCOME_ORDER_ID`) REFERENCES `INCOME_ORDER`(`ID`)
);