CREATE TABLE `OUTCOME_ORDER` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `COMMENT` TEXT DEFAULT NULL,
    `DATE_CREATED` TIMESTAMP NOT NULL,
    `TOTAL_PRICE` DECIMAL(10, 2) NOT NULL,
    `TOTAL_PROFIT` DECIMAL(10, 2) NOT NULL
);

CREATE TABLE `OUTCOME` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `PRODUCT_ID` INT(11) NOT NULL,
    `OUTCOME_ORDER_ID` INT(11) NOT NULL,
    `AMOUNT` DECIMAL(10, 2) NOT NULL,
    `SALE_PRICE` DECIMAL(10, 2) NOT NULL,
    CONSTRAINT `fk_OUTCOME_TO_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCTS`(`ID`),
    CONSTRAINT `fk_OUTCOME_TO_OUTCOME_ORDER` FOREIGN KEY (`OUTCOME_ORDER_ID`) REFERENCES `OUTCOME_ORDER`(`ID`)
);

CREATE TABLE `OUTCOME_TO_INCOME` (
  `OUTCOME_ID` INT(11) NOT NULL,
  `INCOME_ID` INT(11) NOT NULL,
  `AMOUNT` DECIMAL(10, 2) NOT NULL,
  UNIQUE `pk_OUTCOME_TO_INCOME` (`OUTCOME_ID`, `INCOME_ID`),
  CONSTRAINT `fk_OUTCOME_ID_TO_OUTCOME` FOREIGN KEY (`OUTCOME_ID`) REFERENCES `OUTCOME`(`ID`),
  CONSTRAINT `fk_INCOME_ID_TO_INCOME` FOREIGN KEY (`INCOME_ID`) REFERENCES `INCOME`(`ID`)
);